/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as DatabaseRouteImport } from './routes/database'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as OutpostRouteImport } from './routes/outpost'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as ReturnRouteImport } from './routes/return'
import { Route as RoverRouteImport } from './routes/rover'
import { Route as SelectionRouteImport } from './routes/selection'
import { Route as TrainingRouteImport } from './routes/training'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseRoute = DatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const OutpostRoute = OutpostRouteImport.update({
  id: '/outpost',
  path: '/outpost',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnRoute = ReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => rootRouteImport,
} as any)
const RoverRoute = RoverRouteImport.update({
  id: '/rover',
  path: '/rover',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectionRoute = SelectionRouteImport.update({
  id: '/selection',
  path: '/selection',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/database': typeof DatabaseRoute
  '/demo': typeof DemoRoute
  '/landing': typeof LandingRoute
  '/launch': typeof LaunchRoute
  '/outpost': typeof OutpostRoute
  '/planning': typeof PlanningRoute
  '/return': typeof ReturnRoute
  '/rover': typeof RoverRoute
  '/selection': typeof SelectionRoute
  '/training': typeof TrainingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/database': typeof DatabaseRoute
  '/demo': typeof DemoRoute
  '/landing': typeof LandingRoute
  '/launch': typeof LaunchRoute
  '/outpost': typeof OutpostRoute
  '/planning': typeof PlanningRoute
  '/return': typeof ReturnRoute
  '/rover': typeof RoverRoute
  '/selection': typeof SelectionRoute
  '/training': typeof TrainingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/database': typeof DatabaseRoute
  '/demo': typeof DemoRoute
  '/landing': typeof LandingRoute
  '/launch': typeof LaunchRoute
  '/outpost': typeof OutpostRoute
  '/planning': typeof PlanningRoute
  '/return': typeof ReturnRoute
  '/rover': typeof RoverRoute
  '/selection': typeof SelectionRoute
  '/training': typeof TrainingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/database'
    | '/demo'
    | '/landing'
    | '/launch'
    | '/outpost'
    | '/planning'
    | '/return'
    | '/rover'
    | '/selection'
    | '/training'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/database'
    | '/demo'
    | '/landing'
    | '/launch'
    | '/outpost'
    | '/planning'
    | '/return'
    | '/rover'
    | '/selection'
    | '/training'
  id:
    | '__root__'
    | '/'
    | '/apply'
    | '/database'
    | '/demo'
    | '/landing'
    | '/launch'
    | '/outpost'
    | '/planning'
    | '/return'
    | '/rover'
    | '/selection'
    | '/training'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRoute
  DatabaseRoute: typeof DatabaseRoute
  DemoRoute: typeof DemoRoute
  LandingRoute: typeof LandingRoute
  LaunchRoute: typeof LaunchRoute
  OutpostRoute: typeof OutpostRoute
  PlanningRoute: typeof PlanningRoute
  ReturnRoute: typeof ReturnRoute
  RoverRoute: typeof RoverRoute
  SelectionRoute: typeof SelectionRoute
  TrainingRoute: typeof TrainingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database': {
      id: '/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof DatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outpost': {
      id: '/outpost'
      path: '/outpost'
      fullPath: '/outpost'
      preLoaderRoute: typeof OutpostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return': {
      id: '/return'
      path: '/return'
      fullPath: '/return'
      preLoaderRoute: typeof ReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rover': {
      id: '/rover'
      path: '/rover'
      fullPath: '/rover'
      preLoaderRoute: typeof RoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selection': {
      id: '/selection'
      path: '/selection'
      fullPath: '/selection'
      preLoaderRoute: typeof SelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRoute,
  DatabaseRoute: DatabaseRoute,
  DemoRoute: DemoRoute,
  LandingRoute: LandingRoute,
  LaunchRoute: LaunchRoute,
  OutpostRoute: OutpostRoute,
  PlanningRoute: PlanningRoute,
  ReturnRoute: ReturnRoute,
  RoverRoute: RoverRoute,
  SelectionRoute: SelectionRoute,
  TrainingRoute: TrainingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
